export const PROJECTS = [
  {
    name: "Yatta!",
    image: "yatta.svg",
    width: 50,
    height: 50,
    className: "",
    href: "https://yatta-iota.vercel.app/",
  },
  {
    name: "Bantuin",
    image: "bantuin.webp",
    width: 75,
    height: 75,
    className: "filter-none!",
    href: "https://bantuin-by-kcr.vercel.app/",
  },
  {
    name: "Showpedia",
    image: "showpedia.svg",
    width: 50,
    height: 50,
    className: "",
    href: "https://showpedia-by-kcr.vercel.app/",
  },
  {
    name: "Acara",
    image: "acara.svg",
    width: 75,
    height: 75,
    className: "filter-none!",
    href: "https://acara-app.vercel.app/",
  },
  {
    name: "Naike",
    width: 50,
    height: 50,
    className: "",
    image: "",
    href: "https://naike-by-kcr.vercel.app/",
  },
];
